server:
  port: 8901
  
spring:
  application:
    name: microservice-consumer-movie-ribbon

eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://thank:123123@localhost:8761/eureka
  instance:
    prefer-ip-address: true #实例名称显示IP