server:
  port: 8040
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/it-much/config-repo-51cto-video
security:
  basic:
    enabled: true
  user:
    name: thank 
    password: 123123