server:
  port: 8977
  
spring:
  application:
    name: microservice-consumer-movie

# 自己配置的变量, 程序中通过@Value("${user.userServicePath}")来取
user:
  userServicePath: http://localhost:7901/simple/
  
eureka:
  client:
    service-url:
      defaultZone: http://thank:123123@localhost:8761/eureka
  instance:
    prefer-ip-address: true #实例名称显示IP